# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blog}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Dempsey"]
  s.date = %q{2009-11-15}
  s.email = %q{jackdempsey@example.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/blog.rb",
     "lib/blog/blog.rb",
     "lib/blog/config.ru",
     "lib/blog/config/config.rb",
     "lib/blog/config/environments/development.rb",
     "lib/blog/config/environments/production.rb",
     "lib/blog/config/environments/staging.rb",
     "lib/blog/master/config/config.rb",
     "lib/blog/master/config/database.yml",
     "lib/blog/models/blog_entry.rb",
     "lib/blog/script/console",
     "lib/blog/tasks/blog.rake",
     "lib/blog/views/_summary.html.haml",
     "lib/blog/views/base.html.haml",
     "lib/blog/views/root.html.haml",
     "spec/blog_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jackdempsey/pancake-blog}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple blog engine on pancake}
  s.test_files = [
    "spec/blog_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pancake>, [">= 0.1.9"])
    else
      s.add_dependency(%q<pancake>, [">= 0.1.9"])
    end
  else
    s.add_dependency(%q<pancake>, [">= 0.1.9"])
  end
end
